# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'vagrant_ros_guest_plugin.rb'

# To enable rsync folder share change to false
$rsync_folder_disabled = true
$number_of_nodes = 1
$vm_mem = "512"
$vb_gui = false

$hostname = "boxing-%02d"
$boximage = "box-cutter/ubuntu1404-docker"  #either box-cutter/ubuntu1404-docker or rancherio/rancheros


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box   = $boximage

  (1..$number_of_nodes).each do |i|
    hostname = $hostname % i

    config.vm.define hostname do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.memory = $vm_mem
            vb.gui = $vb_gui
        end

        ip = "172.19.8.#{i+41}"
        node.vm.network "private_network", ip: ip
        node.vm.hostname = hostname

    end
  end
end