# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'vagrant_ros_guest_plugin.rb'

# To enable rsync folder share change to false
$number_of_nodes = 1
$vm_mem = "1024"
$vb_gui = false

$hostname = "admin-%02d"
$boximage = "box-cutter/ubuntu1404-docker"  #either box-cutter/ubuntu1404-docker or rancherio/rancheros

def config_node(node, hostname, i)
  node.vm.hostname = hostname
  node_ip = "172.19.8.#{i+99}"
  node.vm.network 'private_network', ip: node_ip
  node.vm.provision :shell, :inline => 'docker run --name=rancher-server -l io.rancher.container.system=rancher-agent --restart=always -d -p 8080:8080 rancher/server:latest', :privileged => true
end

Vagrant.configure(2) do |config|
  config.vm.box   = $boximage

  (1..$number_of_nodes).each do |i|
    hostname = $hostname % i

    config.vm.define hostname do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.memory = $vm_mem
            vb.gui = $vb_gui
        end

        config_node(node, hostname, i)

        node.vm.synced_folder ".", "/opt/rancher", type: "rsync",
            rsync__exclude: ".git/", rsync__args: ["--verbose", "--archive", "--delete", "--copy-links"],
            disabled: true

    end
  
  end
  
end
